'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { projectStories, type ProjectSlug } from '@/lib/project-stories';
export function CaseStudy({slug,initialLanguage='en'}:{slug:ProjectSlug;initialLanguage?:'en'|'mr'}) {
 const [mr,setMr]=useState(initialLanguage==='mr');
 useEffect(()=>{ document.documentElement.lang=mr?'mr':'en'; return ()=>{document.documentElement.lang='en';}; },[mr]);
 const project=projectStories[slug], copy=project[mr?'mr':'en'];
 return <div className="case-study page-shell" lang={mr?'mr':'en'}>
  <a className="skip-link" href="#case-content">{mr?'मुख्य मजकुराकडे जा':'Skip to case study'}</a>
  <nav className="case-nav" aria-label={mr?'प्रकल्प नेव्हिगेशन':'Project navigation'}><a className="ghost-link" href="/#work"><ArrowLeft aria-hidden="true"/>{mr?'सर्व प्रकल्प':'Selected work'}</a><button className="ghost-link" onClick={()=>setMr(!mr)} aria-label={mr?'Switch to English':'Switch to Marathi'} aria-pressed={mr}><span lang="en" className={!mr?'case-language-current':''}>EN</span><span aria-hidden="true"> / </span><span lang="mr" className={mr?'case-language-current':''}>मराठी</span></button></nav>
  <main id="case-content" tabIndex={-1} aria-labelledby="case-title"><header className="case-hero"><p className="label">{mr?'प्रकल्पाची गोष्ट / संकल्पना':'PROJECT STORY / CONCEPT'}</p><h1 id="case-title" lang="en">{project.title}</h1><p className="case-deck">{copy.deck}</p><div className="case-meta"><span>{copy.sector}</span><span>{mr?'स्वतः तयार केलेला डेमो':'Self-initiated demo'}</span></div></header>
  <figure className="case-image"><img src={project.image} width="1200" height="750" alt={`${project.title} — ${mr?'मूळ रंगांतील वेबसाइट पूर्वदृश्य':'website preview in its original colours'}`} fetchPriority="high"/><figcaption>{mr?'डेस्कटॉप पूर्वदृश्य / मूळ रंग':'DESKTOP PREVIEW / ORIGINAL COLOURS'}</figcaption></figure>
  <section className="case-story"><p className="label">01 / {mr?'व्यवसायाचे आव्हान':'BUSINESS PROBLEM'}</p><div><h2>{mr?'पहिली पायरी सोपी करा.':'Make the first step easier.'}</h2><p>{copy.problem}</p></div></section>
  <section className="case-story"><p className="label">02 / {mr?'उपाय व वैशिष्ट्ये':'SOLUTION & FEATURES'}</p><div><h2>{mr?'स्पष्ट उद्देश असलेली रचना.':'Every detail has a job.'}</h2><p>{copy.solution}</p><div className="case-feature-list">{copy.features.map(([title,body],i)=><article key={title}><span className="label">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
  <section className="case-mobile-note"><p className="label">03 / {mr?'स्वतः अनुभव घ्या':'EXPLORE THE EXPERIENCE'}</p><h2>{mr?'तुमच्या स्क्रीनवर पाहा.':'Take a closer look.'}</h2><p>{mr?'फोन किंवा डेस्कटॉपवर मूळ वेबसाइट उघडा आणि मांडणी व संवाद पाहा.':'Open the original website on your phone or desktop to explore the layout and interactions.'}</p><a className="ghost-link" href={project.url} target="_blank" rel="noopener noreferrer">{mr?'लाइव्ह वेबसाइट पहा':'View live website'}<span className="sr-only">{mr?' (नवीन टॅबमध्ये उघडेल)':' (opens in a new tab)'}</span><ArrowUpRight aria-hidden="true"/></a><a className="ghost-link" href="/#automation-demo">{mr?'ऑटोमेशन डेमो वापरा':'Try the automation demo'} →</a></section>
  <section className="case-story"><p className="label">04 / {mr?'अपेक्षित परिणाम':'EXPECTED OUTCOME'}</p><div><h2>{mr?'स्पष्ट उद्दिष्ट. प्रामाणिक अपेक्षा.':'A clear goal. An honest baseline.'}</h2><p>{copy.outcome}</p><p className="case-note">{mr?'हा संकल्पना प्रकल्प आहे. हे डिझाइनचे उद्दिष्ट आहे; ग्राहकाचे प्रमाणपत्र किंवा मोजलेले व्यावसायिक परिणाम नाहीत.':'This is a concept project. These are design goals, not a client endorsement or measured business results.'}</p></div></section>
  </main><footer className="case-footer"><p className="label">{mr?'तुमचा व्यवसाय / पुढची पायरी':'YOUR BUSINESS / NEXT'}</p><h2>{mr?'तुमच्या प्रकल्पाबद्दल बोलूया.':'Let’s talk about your project.'}</h2><a className="ghost-link" href={`https://wa.me/917738400373?text=${encodeURIComponent(`Hi Dev, I saw the ${project.title} concept case study. I would like to discuss a website for my business.`)}`} target="_blank" rel="noopener noreferrer">{mr?'संवाद सुरू करा':'Start a conversation'}<span className="sr-only">{mr?' (WhatsApp नवीन टॅबमध्ये उघडेल)':' (opens WhatsApp in a new tab)'}</span><ArrowUpRight aria-hidden="true"/></a><a className="ghost-link" href="/#work">{mr?'सर्व प्रकल्प':'Back to all work'} →</a></footer>
 </div>;
}
