export const projectStories = {
 'smile-dental': {
  title: 'SMILE DENTAL CLINIC.', image: '/demo-smile-dental.jpg', url: 'https://smile-dental-clinic-demo.dev2404.chatgpt.site/',
  en: { sector: 'Healthcare / Kharghar', deck: 'From treatment research to a clearer appointment enquiry.', problem: 'Someone exploring dental care needs to understand the treatments, find clinic information and know how to request an appointment. Scattered information can make that first step harder than it needs to be.', solution: 'A bilingual clinic website brings treatment information and a guided enquiry into one journey, with contact actions close at hand.', features: [['Treatment discovery','Organised treatment information gives visitors a useful starting point.'],['English + Marathi','The same journey supports two reading preferences.'],['Guided enquiry','A structured request continues on WhatsApp. The clinic confirms availability separately.']], outcome: 'The design aims to make treatment research easier and enquiries more useful to the clinic. In a client project, enquiry completion and confirmed appointments would help evaluate the result.' },
  mr: { sector: 'आरोग्यसेवा / खारघर', deck: 'उपचारांची माहिती ते अपॉइंटमेंटची स्पष्ट चौकशी.', problem: 'दंत उपचारांचा विचार करणाऱ्या व्यक्तीला उपचार समजून घेणे, क्लिनिकची माहिती मिळवणे आणि भेटीसाठी संपर्क करणे सोपे असावे. विखुरलेल्या माहितीमुळे पहिली पायरी अवघड होऊ शकते.', solution: 'दोन भाषांतील वेबसाइटवर उपचारांची माहिती, क्लिनिकचा परिचय आणि टप्प्याटप्प्याने चौकशी एकत्र आणली आहे.', features: [['उपचारांची माहिती','सुव्यवस्थित माहितीमुळे योग्य प्रश्न विचारणे सोपे होते.'],['इंग्रजी + मराठी','दोन्ही भाषांतून माहिती आणि चौकशीची सोय.'],['मार्गदर्शित चौकशी','तयार विनंती WhatsApp वर पुढे जाते. उपलब्धता क्लिनिक स्वतंत्रपणे निश्चित करते.']], outcome: 'उपचारांची माहिती समजणे आणि क्लिनिकला स्पष्ट चौकशी मिळणे हे उद्दिष्ट आहे. प्रत्यक्ष प्रकल्पात पूर्ण झालेल्या चौकशा आणि निश्चित अपॉइंटमेंट्स तपासता येतील.' }
 },
 'bisi-bele': {
  title: 'BISI BELE.', image: '/demo-bisi-bele.jpg', url: 'https://bisi-bele-kharghar.dev2404.chatgpt.site/',
  en: { sector: 'Restaurant / Kharghar', deck: 'Make the food the reason to stay. Make the next step easy to find.', problem: 'A local restaurant visitor usually wants a quick answer: what can I eat, where is it, and how do I take the next step? A food website needs to satisfy curiosity without burying those essentials.', solution: 'A food-first concept pairs the restaurant story with menu discovery and a clear route towards a visit or order enquiry.', features: [['Food-led identity','Original food imagery gives the menu a distinct visual presence.'],['Menu discovery','A focused journey helps visitors explore what is on offer.'],['Local context','Location and practical information support the decision to visit.']], outcome: 'The aim is to help visitors move from browsing food to a useful action. Menu engagement, contact clicks and order enquiries would be meaningful measures in a live client project.' },
  mr: { sector: 'रेस्टॉरंट / खारघर', deck: 'खाद्यपदार्थ पाहा. पुढची पायरी सहज शोधा.', problem: 'स्थानिक रेस्टॉरंटची वेबसाइट पाहताना ग्राहकाला काय खायला मिळेल, ठिकाण कुठे आहे आणि पुढे काय करायचे हे पटकन जाणून घ्यायचे असते.', solution: 'खाद्यपदार्थांना केंद्रस्थानी ठेवून रेस्टॉरंटची गोष्ट, मेनू आणि भेट किंवा ऑर्डरच्या चौकशीकडे जाणारा स्पष्ट मार्ग तयार केला आहे.', features: [['खाद्यपदार्थांची ओळख','मूळ छायाचित्रांमुळे मेनूला स्वतंत्र दृश्य ओळख मिळते.'],['मेनू पाहणे','लक्ष केंद्रित केलेल्या मांडणीमुळे पदार्थ शोधणे सोपे होते.'],['स्थानिक माहिती','ठिकाण आणि उपयुक्त माहिती भेटीचा निर्णय घेण्यास मदत करते.']], outcome: 'खाद्यपदार्थ पाहण्यापासून उपयोगी कृतीकडे नेणे हे उद्दिष्ट आहे. प्रत्यक्ष प्रकल्पात मेनूचा वापर, संपर्क आणि ऑर्डरच्या चौकशा तपासता येतील.' }
 },
 'afterdark': {
  title: 'AFTERDARK.', image: '/demo-afterdark.jpg', url: 'https://afterdark-chocolate.dev2404.chatgpt.site/',
  en: { sector: 'Chocolate / Brand concept', deck: 'A product story you can feel as you scroll.', problem: 'A premium chocolate concept needs to communicate character before a visitor can taste it. The challenge is to make the product memorable while keeping its story and choices readable.', solution: 'A cinematic, dark product experience uses chocolate imagery, restrained typography and scroll-led storytelling to introduce the brand and its flavours.', features: [['Product-first imagery','Chocolate remains the focal point throughout the experience.'],['Scroll storytelling','Motion introduces the product in stages instead of competing with every line of copy.'],['Distinct flavour profiles','Bold, roasted and silky profiles give visitors clear points of comparison.']], outcome: 'The aim is stronger product understanding and a memorable brand impression. Product exploration and onward actions would be useful measures in a live commercial project.' },
  mr: { sector: 'चॉकलेट / ब्रँड संकल्पना', deck: 'स्क्रोल करताना उलगडणारी उत्पादनाची गोष्ट.', problem: 'चव घेण्याआधीच प्रीमियम चॉकलेटचे वैशिष्ट्य जाणवले पाहिजे. उत्पादन लक्षात राहील, पण माहिती वाचायला सोपी असेल, अशी मांडणी करणे हे आव्हान आहे.', solution: 'गडद रंगसंगती, चॉकलेटची दृश्ये, संयत अक्षररचना आणि स्क्रोलसोबत उलगडणारी गोष्ट यांतून ब्रँड व चवींचा परिचय दिला आहे.', features: [['उत्पादन केंद्रस्थानी','संपूर्ण अनुभवात चॉकलेटला महत्त्वाचे स्थान आहे.'],['स्क्रोलसोबत गोष्ट','अॅनिमेशन माहितीशी स्पर्धा न करता उत्पादन टप्प्याटप्प्याने दाखवते.'],['वेगवेगळ्या चवी','बोल्ड, रोस्टेड आणि सिल्की प्रकारांची तुलना करता येते.']], outcome: 'उत्पादन समजणे आणि ब्रँड लक्षात राहणे हे उद्दिष्ट आहे. प्रत्यक्ष व्यावसायिक प्रकल्पात उत्पादनाचा शोध आणि पुढील कृती तपासता येतील.' }
 }
} as const;
export type ProjectSlug = keyof typeof projectStories;
