export const projectStories = {
 'smile-dental': {
  title: 'SMILE DENTAL CLINIC.', image: '/demo-smile-dental.jpg', url: 'https://smile-dental-clinic-demo.dev2404.chatgpt.site/',
  en: { sector: 'Healthcare / Kharghar', deck: 'From treatment research to a clearer appointment enquiry.', problem: 'Someone exploring dental care needs to understand the treatments, find clinic information and know how to request an appointment. Scattered information can make that first step harder than it needs to be.', solution: 'A bilingual clinic website brings treatment information and a guided enquiry into one journey, with contact actions close at hand.', features: [['Treatment discovery','Organised treatment information gives visitors a useful starting point.'],['English + Marathi','The same journey supports two reading preferences.'],['Guided enquiry','A structured request continues on WhatsApp. The clinic confirms availability separately.']], outcome: 'The design aims to make treatment research easier and enquiries more useful to the clinic. In a client project, enquiry completion and confirmed appointments would help evaluate the result.' },
  mr: { sector: 'आरोग्यसेवा / खारघर', deck: 'उपचारांची माहिती ते अपॉइंटमेंटची स्पष्ट चौकशी.', problem: 'दंत उपचारांचा विचार करणाऱ्या व्यक्तीला उपचार समजून घेणे, क्लिनिकची माहिती मिळवणे आणि भेटीसाठी संपर्क करणे सोपे असावे. विखुरलेल्या माहितीमुळे पहिली पायरी अवघड होऊ शकते.', solution: 'दोन भाषांतील वेबसाइटवर उपचारांची माहिती, क्लिनिकचा परिचय आणि टप्प्याटप्प्याने चौकशी एकत्र आणली आहे.', features: [['उपचारांची माहिती','सुव्यवस्थित माहितीमुळे योग्य प्रश्न विचारणे सोपे होते.'],['इंग्रजी + मराठी','दोन्ही भाषांतून माहिती आणि चौकशीची सोय.'],['मार्गदर्शित चौकशी','तयार विनंती WhatsApp वर पुढे जाते. उपलब्धता क्लिनिक स्वतंत्रपणे निश्चित करते.']], outcome: 'उपचारांची माहिती समजणे आणि क्लिनिकला स्पष्ट चौकशी मिळणे हे उद्दिष्ट आहे. प्रत्यक्ष प्रकल्पात पूर्ण झालेल्या चौकशा आणि निश्चित अपॉइंटमेंट्स तपासता येतील.' }
 },
 'rowdy-momo': {
  title: 'ROWDY MOMO.', image: '/demo-rowdy-momo.jpg', url: 'https://rowdy-momo-cafe.vercel.app/',
  en: { sector: 'Nepali café / Bandra West', deck: 'A loud, food-first café site. Steam, plates, and a table you can book.', problem: 'A momo counter gets lost when the menu, the story, and the way to order sit on different pages. People on a phone want the plate first, then a way to order or find the room.', solution: 'A dark, poster-led website puts the steamer up front, then a scroll-linked menu, the café story, and a reserve form in one journey.', features: [['Food-led identity','Studio plates of steam, jhol, crisp, and cold coffee carry the brand.'],['Scroll menu','The platter moves with the scroll, so the menu feels like a counter, not a list.'],['Order and reserve','One red Order button and a reserve form keep the next step obvious.']], outcome: 'The aim is to take someone from the hero plate to an order or a reserved table. Menu opens, order taps, and reserve sends would be the live measures.' },
  mr: { sector: 'नेपाळी कॅफे / बांद्रा वेस्ट', deck: 'मोठा आवाज, खाण्यावर भर. वाफ, प्लेट्स आणि बुक करता येणारी टेबल.', problem: 'मोमो काउंटर हरवतो जेव्हा मेनू, गोष्ट आणि ऑर्डर वेगळ्या पानांवर असतात. फोनवरच्या माणसाला आधी प्लेट हवी, मग ऑर्डर किंवा ठिकाण.', solution: 'गडद, पोस्टरसारख्या साइटवर स्टीमर पुढे आहे, मग स्क्रोलसोबत मेनू, कॅफेची गोष्ट आणि रिझर्व्ह फॉर्म.', features: [['खाण्याची ओळख','स्टीम, झोल, क्रिस्प आणि कोल्ड कॉफीच्या स्टुडिओ प्लेट्स ब्रँड दाखवतात.'],['स्क्रोल मेनू','प्लॅटर स्क्रोलबरोबर सरकतो, यादीसारखा नाही.'],['ऑर्डर आणि रिझर्व्ह','एक लाल ऑर्डर बटण आणि रिझर्व्ह फॉर्म पुढची पायरी स्पष्ट ठेवतात.']], outcome: 'हिरो प्लेटपासून ऑर्डर किंवा बुक केलेल्या टेबलपर्यंत नेणे हे उद्दिष्ट आहे. मेनू, ऑर्डर आणि रिझर्व्ह हे मोजमाप आहेत.' }
 },
 'afterdark': {
  title: 'AFTERDARK.', image: '/demo-afterdark.jpg', url: 'https://afterdark-chocolate.dev2404.chatgpt.site/',
  en: { sector: 'Chocolate / Brand concept', deck: 'A product story you can feel as you scroll.', problem: 'A premium chocolate concept needs to communicate character before a visitor can taste it. The challenge is to make the product memorable while keeping its story and choices readable.', solution: 'A cinematic, dark product experience uses chocolate imagery, restrained typography and scroll-led storytelling to introduce the brand and its flavours.', features: [['Product-first imagery','Chocolate remains the focal point throughout the experience.'],['Scroll storytelling','Motion introduces the product in stages instead of competing with every line of copy.'],['Distinct flavour profiles','Bold, roasted and silky profiles give visitors clear points of comparison.']], outcome: 'The aim is stronger product understanding and a memorable brand impression. Product exploration and onward actions would be useful measures in a live commercial project.' },
  mr: { sector: 'चॉकलेट / ब्रँड संकल्पना', deck: 'स्क्रोल करताना उलगडणारी उत्पादनाची गोष्ट.', problem: 'चव घेण्याआधीच प्रीमियम चॉकलेटचे वैशिष्ट्य जाणवले पाहिजे. उत्पादन लक्षात राहील, पण माहिती वाचायला सोपी असेल, अशी मांडणी करणे हे आव्हान आहे.', solution: 'गडद रंगसंगती, चॉकलेटची दृश्ये, संयत अक्षररचना आणि स्क्रोलसोबत उलगडणारी गोष्ट यांतून ब्रँड व चवींचा परिचय दिला आहे.', features: [['उत्पादन केंद्रस्थानी','संपूर्ण अनुभवात चॉकलेटला महत्त्वाचे स्थान आहे.'],['स्क्रोलसोबत गोष्ट','अॅनिमेशन माहितीशी स्पर्धा न करता उत्पादन टप्प्याटप्प्याने दाखवते.'],['वेगवेगळ्या चवी','बोल्ड, रोस्टेड आणि सिल्की प्रकारांची तुलना करता येते.']], outcome: 'उत्पादन समजणे आणि ब्रँड लक्षात राहणे हे उद्दिष्ट आहे. प्रत्यक्ष व्यावसायिक प्रकल्पात उत्पादनाचा शोध आणि पुढील कृती तपासता येतील.' }
 }
} as const;
export type ProjectSlug = keyof typeof projectStories;
